version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: cloud_storage
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1111:5432"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_files:/app/uploaded_files
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
